"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = "$directory$all$character"

[git_status]
format = '([$all_status$ahead_behind]($style) )'
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
staged = '[+$count](green)'
modified = "📝${count}"

[git_branch]
format = "[$symbol$branch(:$remote_branch)]($style) "

[python]
format = '[${pyenv_prefix}(\($virtualenv\) )]($style)'

[golang]
symbol = " "
